version: "3"

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"