# Generated by Django 3.1.2 on 2020-11-30 19:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/avatars/default_avatar/av.png', upload_to=app.models.avatar_upload_to, verbose_name='Аватар'),
        ),
    ]
